name: Build nvim

# Run this workflow every time a new commit pushed to your repository
on:
  workflow_dispatch
  # push:
  #   branches: master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: Build & Push
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push ubuntu-dev-base
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: images/ubuntu-dev-base
          tags: albandiguer/ubuntu-dev-base:latest
          push: true
      - name: Build & push power-tmux
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: images/power-tmux
          tags: albandiguer/power-tmux:latest
          push: true
      - name: Build & push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: images/nvim
          tags: albandiguer/nvim:latest
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
